### ISSUE TITLE
make sure tests run with '--isolation'

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#289]
see #214 for a case where the tests missed a regression because they're not isolated.

**Comment by zhang-alvin** [comment]
The example in the PR runs into an error when nosetests is used without the `--isolation` option. Since we've moved over to the py.tests framework, I think this issue is no longer relevant. Moreover we have the py.tests equivalent option `--boxed` in the [Makefile](https://github.com/erdc-cm/proteus/blob/master/Makefile#L308).
