### ISSUE TITLE
velocity post-processing for porous media in RANS2P

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#400]
I think the velocity post-processing algorithm needs updating to  the case when porosity < 1. It  appears to be called  with the fluid  microscopic velocity rather than the volume-averaged velocity. 
/cc @Giovanni-Cozzuto-1989  @adimako

**Comment by adimako** [comment]
@cekees I remember confirming with Giovanni that velocity is not the VA one. Giovanni has done extended checks. This does not pose any issue as long as equations are coded with the fluid velocity, rather than the VA one. The real issue is some v & v results at the semi-infinite porous domain that we never get to the bottom of it. I am closing this because we believe equations are not to blame
